= Andrea Thniah - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: NoteNote

---

== Overview

NoteNote is a desktop project application used for managing multiple projects and tasks. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *the ability to create group tags and apply them to tasks*
** What it does: allows users to create a group tag and add multiple child tags into it
** Justification: multiple tags can be repetitive to type out again and again especially if they are used often. This enhancement aims to reduce typing errors and allows a convenient way for users to easily create a group tag and apply them to different tasks.
** Highlights: This enhancement is split between `DefineTag` which creates a group tag and `AddTag` that applys existing group tag to a task. They should be used in conjunction.

* *Minor enhancement*: added a `listtag` command that allows the user to list down all tags and its associated task.

* *Code contributed*: [https://nuscs2113-ay1819s2.github.io/dashboard-beta/#search=andreathniah[Functional code]] [https://nuscs2113-ay1819s2.github.io/dashboard-beta/#search=andreathniah[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Handled all Github related issues that arised within the team (merge conflicts, rebasing etc)
*** Managed releases `v1.0` - `v1.4` (4 releases) on GitHub
** Enhancements to existing features:
*** Morphing AB4 to NoteNote
*** Updated the GUI tag color scheme (Pull requests https://github.com/CS2113-AY1819S2-T09-3/main/pull/19[#19])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=listtag]

include::../UserGuide.adoc[tag=definetag]

include::../UserGuide.adoc[tag=addtag]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=listtag]

include::../DeveloperGuide.adoc[tag=definetag]

include::../DeveloperGuide.adoc[tag=addtag]
