= Yow Ren Jie - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: NoteNotex
---

== Overview

NoteNote is a desktop project application used for managing multiple projects and tasks. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.
== Summary of contributions

* *Major enhancement*: added *the ability to view command history for each individual task*
** What it does: allows the user to view a command history of a chosen task with the command `taskhistory`. The command history will include commands that have a direct impact on the task (e.g. edit / completed / grouptag / delete)
** Justification: Current implementation will only allow you to view the command history of every command (valid & invalid) that has been entered.
But when handling multiple large projects, a user is bound to have numerous edits for the many task that is there.
In this case the likelihood of a user forgetting / executing a wrong command is very probable. Thus, this feature allows a user
to view a record of the changes he made for a specific task instead of viewing it as a whole project. Allowing easy referencing for a user.
** Highlights: This feature is implemented by creating another stack parallel to the existing command history stack. This new stack will contain the unique ID of a task corresponding
to the command of the same index in the command history.

* *Minor enhancement*: added *the ability to compare a task to its previous version*
** What it does: allows the user to view a direct comparison of a chosen task against its previous version before the edit with the command `compare`
** Justification: To allow easy referencing for a chosen task in a neater method as this feature compares the differences and will only show you the result of the field (Name / Description / Deadline) that was changed, instead of all the field.
** Highlights: Current undo feature is implemented as general undo for all commands.
This compare feature serves as a base for a future feature which allows undo for a specific task where a user is able to undo to the version that is shown when `compare` executes.

* *Code contributed*: [https://nuscs2113-ay1819s2.github.io/dashboard-beta/#search=&timeframe=day&reverse=false&groupSelect=groupByRepos&breakdown=false&tabAuthor=arhjaye&tabRepo=CS2113-AY1819S2-T09-3_main_master&sort=displayName&since=2019-02-10&until=2019-04-01[Reposense]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.2` - `v1.3` (2 releases) on GitHub
*** Ensured deliverable's are met.
** Enhancements to existing features:
*** Fixed existing tests cases to be based on new model infrastructure. (Pull requests https://github.com/CS2113-AY1819S2-T09-3/main/pull/107[#107])
*** Ensure code coverage is met during product release.
*** Display total projects within UI Status Bar Footer (Pull requests https://github.com/CS2113-AY1819S2-T09-3/main/pull/17[#17])
** Documentation:
*** Updated DeveloperGuide & UserGuide to include feature implementations.
*** Update diagrams for DeveloperGuide to reflect existing architecture used.
*** Added user stories & use cases for DeveloperGuide
*** Managed formatting for UserGuide to ensure proper structuring and consistency.
*** Added content for UserGuide for Task Level Commands.
** Community:
*** Reported bugs & solutions to team (examples:  https://github.com/CS2113-AY1819S2-T09-3/main/issues/97[#97], https://github.com/CS2113-AY1819S2-T09-3/main/pull/128[#128], https://github.com/CS2113-AY1819S2-T09-3/main/pull/131[#131])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=UIlayout]

include::../UserGuide.adoc[tag=compare]

include::../UserGuide.adoc[tag=taskhistory]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=compare]

include::../DeveloperGuide.adoc[tag=taskhistory]

