= Josephine Tanadi - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: NoteNote

---

== Overview

NoteNote is a desktop project application used for managing multiple projects and tasks. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *the ability to import and export projects*
** What it does: imports new projects from a JSON file and exports selected existing projects to a JSON file
** Justification: This feature allows users to share projects with another user without the other user having to add projects and tasks manually.
** Highlights: The implementation was challenging as it requires us to change the current Storage Model to contain both projects and tasks.

* *Major enhancement*: *modified UI, Logic, Model and Storage components to suit NoteNote*
** What it does: loads project list upon start up and allows navigation between projects and tasks.
** Justification: This feature provides the background logic for users to interact with multiple projects and multiple tasks within each individual projects.
** Highlights: The implementation was challenging as it requires us to modify all existing components to suit our application.

* *Minor enhancement*:
** Updated the GUI to include a Project List Panel and Task List Panel
** Updated the storage to store tasks within project and project within project list
** Minor modification to Add, Edit, Select, Delete and Clear command to support new project list model

* *Code contributed*: [https://nuscs2113-ay1819s2.github.io/dashboard-beta/#search=josephinetanadi[Functional code]]

* *Other contributions*:

** Enhancements to existing features:
*** Modified system tests for existing features:
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide:
*** Did cosmetic tweaks to existing contents of the Developer Guide:

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=importexport]

