= Rachel Lim - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: NoteNote

---

== Overview

NoteNote is a desktop project application used for managing multiple projects and tasks. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *the ability to mark tasks as completed*
** What it does: allows the user to mark specific tasks as completed by displaying a `completed` tag for each of those tasks. This can be reversed by using the undo command.
** Justification: This feature improves the product significantly because a user can conveniently check off tasks that are completed, which ties in with the task-management purpose of this project.
** Highlights: This enhancement required a different implementation from `edit` as it was more specialised and only affected the tags of a task. Any tasks marked as completed would also have to be retained in Storage, to complement the `analyse` feature.

* *Major enhancement*: added *the ability to analyse all completed tasks*
** What it does: allows the user to see which tasks in a specific project have been completed already, so as to track the user's progress on that project.
** Justification: This feature improves the product significantly because a user can conveniently check off tasks that are completed, which ties in with the task-management purpose of this project.
** Highlights: This enhancement required additional implementations as the current `find` command could only search through names of tasks, but `analyse` needed to search through tags instead and present the results as a countable statistic.

* *Minor enhancement*: added command aliases that allow the user to cut down the amount of typing to execute any command.

* *Code contributed*: [https://nuscs2113-ay1819s2.github.io/dashboard-beta/#search=rachellim10[Functional code]]

* *Other contributions*:

** Enhancements to existing features:
*** Added shorthand command aliases for existing commands
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide
*** Did cosmetic tweaks to existing contents of the Developer Guide

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=analyse]

include::../UserGuide.adoc[tag=completed]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

